[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = ['python']
[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']


[[plugins]]
repo = 'lervag/vim-latex'
on_ft = ['tex']